blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/cashapp/sqldelight/discussions
    about: If you want to ask how to do something, or to understand why something isn't working the way you expect it to, use GitHub Discussions.
